### ISSUE TITLE
Error a cargar el modelo en la jetson

### ISSUE THREAD

**Issue by Franco-A01733927** [Manchester-Robotics/ROSApril2022_Students#19]
Al momento de correr nuestro código con la red neuronal ya entrenada nos lanza el siguiente error.

![Screenshot from 2022-06-09 18-10-25](https://user-images.githubusercontent.com/67660198/172960124-f8b67e0b-2257-45b3-9ecb-e9b375bb5abd.png)
__Traceback (most recent call last):
  File "/home/puzzlebot/reto_ws/src/vision_p/src/signRoad.py", line 109, in <module>
    my_node =  SignDetect()
  File "/home/puzzlebot/reto_ws/src/vision_p/src/signRoad.py", line 30, in __init__
    self.model = load_model("signs_cnn.h5") /home/puzzlebot/reto_ws/src/vision_p/src
  File "/usr/local/lib/python3.6/dist-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.6/dist-packages/keras/saving/saved_model/load.py", line 108, in load
    meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 121, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: signs_cnn.h5/{saved_model.pbtxt|saved_model.pb}__

El código que estamos usando es el siguiente:

![Screenshot from 2022-06-09 18-13-18](https://user-images.githubusercontent.com/67660198/172960224-829966a3-6f93-426f-a1bc-7877b241a09a.png)

Ya probamos agregando la ruta completa y con "./" antes del nombre, el modelo entrenado se encuentra en la misma carpeta que el archivo py

**Comment by SanthA25** [comment]
El formato de nuestro modelo está como "modelo.h5"

**Comment by rebecavelasco** [comment]
Hola,  

Por lo que vemos, lo unico que puedo pensar es que sea el path. Hay varios puntos que podriamos probar:

Inicialmente, el path. el siguiente codigo  es un ejemplo que te puede ayudar a crear el path correcto.  
```
  rp = rospkg.RosPack()
        script_path = os.path.join(rp.get_path("sign_rec"), "src", "saved_model","my_model")
```
Revisa que concida con el orden de tus carpetas. 

Si aun tienes problemas, compartenos como esta tu workspace para tener una mejor idea,
